image: ghcr.io/home-asst/{arch}-base-ubuntu
build_from:
  aarch64: "arm64v8/ubuntu:"
  armv7: "arm32v7/ubuntu:"
  amd64: "ubuntu:"
cosign:
  identity: https://github.com/home-asst/docker-base/.*
args:
  BASHIO_VERSION: 0.16.2
  TEMPIO_VERSION: 2024.12.1
  S6_OVERLAY_VERSION: 3.1.6.2
labels:
  io.hass.base.name: ubuntu
  org.opencontainers.image.source: https://github.com/home-asst/docker-base
