image: ghcr.io/home-asst/{arch}-base-debian
build_from:
  aarch64: "arm64v8/debian:"
  armv7: "arm32v7/debian:"
  armhf: "arm32v5/debian:"
  amd64: "debian:"
  i386: "i386/debian:"
cosign:
  identity: https://github.com/home-asst/docker-base/.*
args:
  BASHIO_VERSION: 0.16.2
  TEMPIO_VERSION: 2024.12.1
  S6_OVERLAY_VERSION: 3.1.6.2
labels:
  io.hass.base.name: debian
  org.opencontainers.image.source: https://github.com/home-asst/docker-base
